ipa_usergroup { 'test':
  ensure      => present,
  description => 'Test groep',
  gid         => '1025', # by default, gid is autogenerated and it is advised to leave it that way
  posix       => false,  # defaults to true
  external    => true    # defaults to false
}
